on:
  push:
    branches: [ master ]
jobs:
  deploy-laboratory:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Build site-test (Vue)
        run: |
          cd site-test
          npm install
          npm run staging_ru
          cp staging/index.html staging/404.html
          mkdir -p ../games
          cp -r ./staging/* ../games/

      - name: Build ru-site-test
        run: |
          cd ../
          echo "Uploads folder content:"
          ls -l ./uploads
          npm install
          npx gulp

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./