name: Deploy RU site to another repo

on:
  repository_dispatch:
    types: [ deploy_ru ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read       # we only need read on the source repo
      pages: write         # needed by the gh-pages action
      id-token: write

    steps:
      # 1) Check out *this* repo’s code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Build your staging-ru directory
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install & Build (staging-ru)
        run: |
          npm install
          npm run staging-ru
          cp staging/index.html staging/404.html

      # 3) Deploy to GH Pages in the other repo
      - name: Deploy to GitHub Pages (other-repo)
        uses: peaceiris/actions-gh-pages@v4
        with:
          # NOTE: GITHUB_TOKEN can't push into another repo => use PAT
          personal_token: ${{ secrets.TARGET_PAT }}
          publish_branch: gh-pages
          publish_dir: ./staging
          publish_repo: my-org/other-repo
          # optional: clean out old files in that repo’s gh-pages
          clean: true
          # you can also override commit author/message if you like:
          # user_name: github-actions[bot]
          # user_email: github-actions[bot]@users.noreply.github.com
          # commit_message: "ci: deploy RU build to other-repo"
